manicursos/apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.NoticiaListView.as_view(), name="blog"),
    path('noticia/<int:id>', views.detail_noticia, name="noticia"),
    path('contato/', views.contato, name="contato"),
]

manicursos/apps/curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
    path('cursos/', views.cursos, name="cursos"),
    path('', views.home, name="home"),
    path('sobre/', views.sobre, name="sobre"),
]

manicursos/manicursos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='curso/')),
    path('admin/', admin.site.urls),
    path('curso/', include('apps.curso.urls')),
    path('blog/', include('apps.blog.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manicursos/apps/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    subtitulo = models.CharField(max_length=300)
    criador = models.CharField(max_length=200)
    datatime_da_pub = models.DateTimeField(auto_now=True)
    conteudo = models.TextField()
    imagem = models.ImageField(upload_to="noticias/")
    data = models.DateField(default=timezone.now)

    def __str__(self):
        return self.titulo

class Contato(models.Model):
    ASSUNTO_CHOICES = [
        ("1", "Reclamação"),
        ("2", "Dúvidas"),
        ("3", "Critica"),
        ("4","Ajuda"),
        ("5","Outro"),
    ]

    assunto = models.IntegerField(choices=ASSUNTO_CHOICES)
    nome = models.CharField(max_length=200)
    email = models.EmailField()
    mensagem = models.TextField() 

    def __str__(self):
        return f'assunto: {self.assunto} - {self.nome} - {self.email}'

manicursos/apps/curso/models.py
from django.db import models
from django.db.models import Avg
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Curso(models.Model):
    #definindo alguns choices
    NIVEL_CHOICES = [
        ("1","superior"),
        ("2","técnico"),
    ]
    MODALIDADE_CHOICES = [
        ("1", "presencial"),
        ("2", "semipresencial"),
        ("3", "online"),
    ]
    AREA_CHOICES = [
        ("1", "Ciências Humanas"),
        ("2", "Ciências Exatas"),
        ("3", "Biociências"),
    ]
    
    #definindo os campos do modelo
    nome = models.CharField(max_length=200)
    nota = models.DecimalField(max_digits=2, decimal_places=1, blank=True, default=0.00)
    nivel = models.IntegerField(choices=NIVEL_CHOICES)
    modalidade = models.IntegerField(choices=MODALIDADE_CHOICES)
    carga_horaria = models.IntegerField()
    descricao = models.TextField()
    imagem = models.ImageField(upload_to="cursos/")
    preco = models.DecimalField(max_digits=7, decimal_places=3)
    area = models.IntegerField(choices=AREA_CHOICES)

    @property
    def atualizar_media(self):
        media = self.avaliacao_set.aggregate(media=Avg('nota'))['media']
        self.nota = media
        self.save()

    def __str__(self):
        return self.nome

class Aluno(models.Model):
    STATUS_CHOICES = [
        ("1", "formado"),
        ("2", "cursando"),
    ]
    #definindo os campos do modelo
    nome = models.CharField(max_length=200)
    curso = models.ManyToManyField(Curso)
    status = models.IntegerField(choices=STATUS_CHOICES)
    data_entrada = models.DateField()
    data_saida = models.DateField(blank=True, null=True)
    imagem = models.ImageField(upload_to="cursos/alunos/")

    def save(self, *args, **kwargs):
        if self.status == 1 and not self.data_saida:
            raise ValueError('data de saida é obrigatória para alunos formados!')
        super().save(*args,**kwargs)

    def __str__(self):
        return self.nome
    
class Professor(models.Model):
    TITULACAO_CHOICES = [
        ("1", "doutor"),
        ("2", "mestre"),
    ]
    nome = models.CharField(max_length=200)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    titulacao = models.IntegerField(choices=TITULACAO_CHOICES)
    imagem = imagem = models.ImageField(upload_to="cursos/professores/")

    def __str__(self):
        return f'{self.nome} - {self.titulacao}'

class Avaliacao(models.Model):
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    nota = models.DecimalField(max_digits=2,decimal_places=1)
    comentario = models.TextField()

    def __str__(self):
        return f'curso = {self.curso.nome} - nota ({self.nota})'

@receiver(post_save, sender=Avaliacao)
def atualizar_media_curso(sender, instance, **kwargs):
    instance.curso.atualizar_media

manicursos/apps/blog/forms.py
from django import forms
from .models import Contato

class FormContato(forms.ModelForm):
    class Meta:
        model = Contato
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['assunto'].widget.attrs.update({
            'class': 'assunto',
            'name': 'Assunto',
            'autocomplete': 'off',
        })
        
        self.fields['nome'].widget.attrs.update({
            'class': 'nome',
            'placeholder': "Nome",
            'autocomplete': 'off',
        })

        self.fields['email'].widget.attrs.update({
            'class': 'email',
            'placeholder': "Email",
            'autocomplete': 'off',
        })

        self.fields['mensagem'].widget.attrs.update({
            'class': 'mensagem',
            'placeholder': "Mensagem",
            'autocomplete': 'off',
        })

manicursos/apps/blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Noticia, Contato
from .forms import FormContato
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse

class NoticiaListView(generic.ListView):
    model = Noticia
    template_name = "blog/noticias.html"
    context_object_name = "noticias"
    paginate_by = 6

def detail_noticia(request, id):
    noticia = Noticia.objects.get(id=id)
    
    return render(request, "blog/detail_noticia.html", {
        "noticia": noticia,
    })
      
def contato(request):
    if request.method == "POST":
        form_contato = FormContato(request.POST)
        if form_contato.is_valid():
            assunto = form_contato.cleaned_data["assunto"]
            assunto_display = dict(Contato.ASSUNTO_CHOICES)[int(assunto)]
            email = form_contato.cleaned_data["email"]
            nome_usuario = form_contato.cleaned_data["nome"]
            mensagem = f"caro {nome_usuario}, \nseu email com assunto {assunto_display} será repondido em breve..."
            send_mail(
                assunto_display,
                mensagem,
                settings.EMAIL_HOST_USER,  # Email remetente
                [email],  # Lista de destinatários
                fail_silently=False,
            )
            contato = Contato(assunto=assunto,nome=nome_usuario,email=email,mensagem=form_contato.cleaned_data["mensagem"])
            contato.save()
        return HttpResponseRedirect(reverse('blog:contato'))
    else:
        form_contato = FormContato()    
    return render(request, "blog/contato.html", {
        "form_contato": form_contato,
    })

manicursos/apps/curso/views.py
from django.shortcuts import render
from django.views import generic
from .models import Curso, Aluno, Professor

def home(request):
  #retornar os cursos (3) que possuiem a nota maior
  cursos = Curso.objects.all().order_by('nota')[len(Curso.objects.all())-3:]
  #retornar os 10 primeiros alunos
  alunos = Aluno.objects.all()[:10]
  return render(request, "curso/home.html", {
    "cursos": cursos,
    "alunos": alunos,
  })

def sobre(request):
  professores = Professor.objects.all()
  return render(request, "curso/sobre.html", {
    "professores": professores,
  })

def cursos(request):
  cursos_populares = Curso.objects.all().order_by('nota')[len(Curso.objects.all())-3:]
  cursos_humanas = Curso.objects.filter(area=1)[:4]
  cursos_exatas = Curso.objects.filter(area=2)[:4]
  cursos_bio = Curso.objects.filter(area=3)[:4]
  alunos = Aluno.objects.all()
  return render(request, "curso/cursos.html", {
    "cursos_humanas": cursos_humanas,
    "cursos_exatas": cursos_exatas,
    "cursos_bio": cursos_bio,
    "cursos_populares": cursos_populares,
    "alunos": alunos,
  })

manicursos/core/templates/base.html
<!---------------------------------- base template -------------------------------------------->
<!DOCTYPE html>
{% load static %}
<html>

   <head>

    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    
    <!--- links para fontes-->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    
    <!-- arquivos estaticos css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    
    {% block style %}{% endblock %}

   </head>

   <body>

    <!-------------------------------NAVBAR--------------------------------------->
    <div class="barra">

        <div class="imagem">
            <a href="{% url 'curso:home' %}">
                <img src="{% static 'img/manilogo.svg' %}">
            </a>
        </div>
        
        <div class="flex center"><p class="line"></p></div> 

        <div class="frame">

            <a class="frame" href = "{% url 'curso:home' %}">HOME</a>
            <a class="frame" href = "{% url 'curso:sobre' %}">SOBRE</a>
            <a class="frame" href = "{% url 'curso:cursos' %}">CURSOS</a>
            <a class="frame" href = "{% url 'blog:blog' %}">BLOG</a>
            <a class="frame" href = "{% url 'blog:contato' %}">CONTATO</a>

        </div>

    </div>

     <!---------------------------------FINAL DO NAVBAR-------------------------------------------->
    
     <!---------------------------------------MAIN------------------------------------------------>

    {% block main%}{% endblock %}

    {% block script %}{% endblock %} 
    <!-- scripts js-->
    <script src="{% static 'js/slider.js' %}"></script>

      <!----------------------------INÍCIO DO FOOTER------------------------------------------------>
    <div class="base">

        <a href="{% url 'curso:home' %}">
            <img class="logo" src="{% static 'img/manilogo.svg' %}">
        </a>
        
        <div class="bloco-principal">

           <div class="bloco-1">

            <h4>Entre em contato</h4>

            <p>contato@manicursos.com.br</p>
            <p>+1-2345-6789</p>
            <p>23 Cornelia St, NY 10014, EUA</p>
            <a href="https://www.facebook.com/ejectufrn/" target="_blank">
                <img class="redes" src="{% static 'img/redes_sociais.svg' %}"> 
            </a>
            

           </div>

           
           <div class="bloco-2">

            <h4>FAQ</h4>

            <p>Auctor volupat.</p>
            <p>Fermentum turpis.</p>
            <p>Mi consequat.</p>
            <p>Amet venenatis.</p>
            <p>Convalis porttitor.</p>

           </div>

           <div class="bloco-3">

            <h4>Central de Ajuda</h4>

            <p>Egestas vitae.</p>
            <p>Viverra Iorem ac.</p>
            <p>Eget ac tellus.</p>
            <p>Erat nulla.</p>
            <p>Vulputate proin.</p>

           </div>


        </div>

        <div class="copyright">

            <p>Copyright © 2023. All rights reserved.</p>
            
           </div>
           

       
    </div>

    <!---------------------------FINAL DO FOOTER--------------------------->

   </body>

</html>

manicursos/core/templates/blog/noticias.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Manicursos | Noticias {% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
{% endblock %}

{% block main %}
<header>
    <div class="headline-container">
        <h1 class="headline-h1">Últimas Notícias</h1>
        <p class="headline-p">Est recusandae fugit qui quia voluptas ut ratione</p>
        <p class="headline-p">iusto aut accusamus voluptatem.</p>
    </div>
</header>

<div class="flex end">
    <div class="busca">
        <input type="text" class="txtBusca" placeholder="Buscar curso"/>
        <div class="box-img">
            <img class="lupa" src="{% static 'img/graphics/search-outline.svg' %}" alt="Buscar"/>
        </div>
    </div>
</div>


<div class="banner-container">
    {% for noticia in noticias %}
    <div class="banner-card">
        <img class="banner-imagem" src="{{noticia.imagem.url}}" alt="Imagem Banner">
        <h1 class="banner-titulo">{{noticia.titulo}}</h1>
        <p class="banner-paragrafo">{{noticia.subtitulo}}</p>
        <p class="banner-data"><img src="{% static 'img/graphics/icon-heart.png' %}">10 de outubro de 2023</p>
        <a href="{% url 'blog:noticia' noticia.id %}" class="banner-bottom">LER MAIS</a>
        </div>
    {% endfor %}
    <div class="custom-button">Carregar mais</div>
</div>
{% endblock%}

manicursos/core/templates/curso/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    
    <!--- links para fontes-->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/cursos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/aluno-aprova.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/barra.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/imagens-laterais.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"> 
     

</head>
<body>

    <div  style="float: inline-start; clear: none;" class="barra">

        <div class="imagem">
            <a href="{% url 'curso:home' %}">
                <img src="{% static 'img/manilogo.svg' %}">
            </a>
        </div>

        <!--  <img class="imagem" src="../img/manilogo.svg"> -->
        
        <div><p class="line"></p></div> 

        <div style="border-bottom: 10px solid white;" class="frame">

          <!-- <div><p class="line"></p></div> -->

          <a class="frame" href = "{% url 'curso:home' %}">HOME</a>
            <a class="frame" href = "{% url 'curso:sobre' %}">SOBRE</a>
            <a class="frame" href = "{% url 'curso:cursos' %}">CURSOS</a>
            <a class="frame" href = "{% url 'blog:blog' %}">BLOG</a>
            <a class="frame" href = "{% url 'blog:contato' %}">CONTATO</a>

        </div>

     </div>


    <div class="imagens-laterais">

        <div class="lateral-6">
            <img src="{% static 'img/home/lateral-6.png' %}">
        </div>
    
        <div class="lateral-5">
            <img src="{% static 'img/home/lateral-5.png' %}">
        </div>
    
        <div class="lateral-4">
            <img src="{% static 'img/home/lateral-4.png' %}">
        </div>
    
        <div class="lateral-3">
            <img src="{% static 'img/home/lateral-3.png' %}">
        </div>
    
        <div class="lateral-2">
            <img src="{% static 'img/home/lateral-2.png' %}">
        </div>
    
        <div class="lateral-1">
            <img src="{% static 'img/home/lateral-1.png' %}">
        </div>
    
    </div>
    
      <header>
    
        <div class="box-header">
            <h1 style="margin-top: -830px;">Bem vindo a educação <span class="barraLaranja">Mani</span> de <span class="text-orange">qualidade</span></h1>
            
            <div class="subtitle">
                <p>Com a<span class="inline mani-cursos"> Mani cursos </span> você pode ficar tranquilo, seu futuro está em boas mãos</p>
            </div>
            
            <div class="explorar flex">
                
                <a class="link-explorar" href="{% url 'curso:cursos' %}">
                    <div class="circle-explorar bg-orange">
                        <img src="{% static 'img/graphics/Line.svg' %}" alt="">
                    </div>
                    <p class="text-explorar">explorar cursos</p>
                </a>
    
                <div class="estudando flex">
                    <div class="circles">
                        <div class="circle-aluno"><img src="{% static 'img/home/icon 001 1.svg' %}" alt=""></div>
                        <div class="circle-aluno"><img src="{% static 'img/home/icon 002 1.svg' %}" alt=""></div>
                        <div class="circle-aluno"><img src="{% static 'img/home/icon 003 1.svg' %}" alt=""></div>
                    </div>
                    <p>78.926 alunos</p>
                    <p>estudando agora</p>
                </div>
            
            </div>
    
        
        </div>
    
        <div class="fotos">
    
        </div>
    
    </header>
    
    <div class="circle-full c1 bg-orange"></div>
    <div class="circle-full c2 bg-orange"></div>
    <div class="circle-full c3 bg-orange"></div>
    <div class="circle-full c4 bg-orange"></div>
    
    <div class="circle-full2 c-1 bg-black"></div>
    <div class="circle-full2 c-2 bg-black"></div>
    
    <div class="circle-empty c-1-1"></div>
    <div class="circle-empty-1 c-1-2"></div>
    
    <div class="circle-full-70 bg-black"></div>
    
    <div class="circle-dotted bg-black"></div>
    
    <!--------------------------------- cursos mais populares --------------------------------------->
    <section>
        <h1 class="fs-45">Cursos mais populares</h1>
        
        <div class="box-right">
    
            <div class="circle">
                <img class="arrow-left" src="{% static 'img/graphics/seta-direita.png' %}" alt="arrow-left">
            </div>
            <div class="circle">
                <img src="{% static 'img/graphics/seta-direita.png' %}" alt="arrow-right">
            </div>
        </div>
    
        <div class="card-master">
            {% for curso in cursos %}
                <div class="card">
    
                    <div class="img-card">
                        <img src="{{curso.imagem.url}}" alt="imagem-curso-{{curso.nome}}">
                    </div>
    
                    <div class="card-header">
                        <h1 class="card-title">{{curso.nome}}</h1>
                        <div class="avaliacao">   
                            <img src="{% static 'img/graphics/estrela.png' %}" alt="estrela">
                            <p>({{curso.nota}})</p>
                        </div>
                    </div>
    
                    <h2>{{curso.get_modalidade_display}} - {{curso.carga_horaria}}h semanais - {{curso.get_nivel_display}}</h2>
    
                    <p class="descricao">{{curso.descricao}}</p>
    
                    <div class="card-footer">
                        <div class="preco">
                            <p class="preco-destaque">24x de R$ 410,90</p>
                            <p class="preco-a-vista">ou R${{curso.preco}} à vista</p>
                        </div>
                        <button>ver mais</button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    
    <!---------------------------------------- nossa historia --------------------------------------->
    
    <div class="box-nossa">
        <div class="container">
            <div class="carrossel carrossel-tam">
                <div class="img-carrossel img1">
                    <img src="../../static/img/sobre/PH HIST 001.jpg" alt="">
                </div>
                <div class="img-carrossel img2">
                    <img src="../../static/img/sobre/PH HIST 002.jpg" alt="">
                </div>
                <div class="img-carrossel img3">
                    <img src="../../static/img/sobre/PH HIST 003.jpg" alt="">
                </div>
                
            </div>
            <div class="nav">
                <div class="circle-carrossel active"></div>
                <div class="circle-carrossel"></div>
                <div class="circle-carrossel"></div>
            </div>
        </div>
        
        <div class="textoUm">
            <h1 class="titulos">Nossa <span class="barraLaranja">História</span></h1>
            <p id="descricaoUm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et
                dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
        </div>
    </div>
    
    <!---------------------------------- quem já foi aluno aprova! ----------------------------------->
    
    <div class="box-aluno">
        <h1 class="mb-50 fs-45">Quem já foi aluno <span class="text-orange">aprova!</span></h1>
        
        <div class="slider-aluno">
            {% for aluno in alunos %}
            <div class="card-aluno">
                <img class="br-40" src="{{aluno.imagem.url}}" alt="">
                <div class="descricao-aluno">
                    <p class="p-nome">{{aluno.nome}}</p>
                    <p class="p-curso">{{aluno.curso.nome}} ({{aluno.data_entrada}}-{{aluno.data_saida}})</p>
                    <p class="p-descricao">"lorem ipsum dolor sit amet consectetur. id nunc ultrices eget risus at accumsan. Urna</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="base">

        <a href="{% url 'curso:home' %}">
            <img class="logo" src="{% static 'img/manilogo.svg' %}">
        </a>
        
        <div class="bloco-principal">

           <div class="bloco-1">

            <h4>Entre em contato</h4>

            <p>contato@manicursos.com.br</p>
            <p>+1-2345-6789</p>
            <p>23 Cornelia St, NY 10014, EUA</p>
            <a href="https://www.facebook.com/ejectufrn/" target="_blank">
                <img class="redes" src="{% static 'img/redes_sociais.svg' %}"> 
            </a>
            

           </div>

           
           <div class="bloco-2">

            <h4>FAQ</h4>

            <p>Auctor volupat.</p>
            <p>Fermentum turpis.</p>
            <p>Mi consequat.</p>
            <p>Amet venenatis.</p>
            <p>Convalis porttitor.</p>

           </div>

           <div class="bloco-3">

            <h4>Central de Ajuda</h4>

            <p>Egestas vitae.</p>
            <p>Viverra Iorem ac.</p>
            <p>Eget ac tellus.</p>
            <p>Erat nulla.</p>
            <p>Vulputate proin.</p>

           </div>


        </div>

        <div class="copyright">

            <p>Copyright © 2023. All rights reserved.</p>
            
           </div>
           

       
    </div>

    <script src="{% static 'js/carrossel.js' %}"></script>    
</body>
</html>

manicursos/core/templates/curso/sobre.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Manicursos | Sobre {% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
{% endblock %}

{% block main %}

<div class="containerUm">
    <div class="container">
        <div class="carrossel carrossel-tam1">
            <div class="img-carrossel img1">
                <img src="../../static/img/sobre/PH HIST 001.jpg" alt="">
            </div>
            <div class="img-carrossel img2">
                <img src="../../static/img/sobre/PH HIST 002.jpg" alt="">
            </div>
            <div class="img-carrossel img3">
                <img src="../../static/img/sobre/PH HIST 003.jpg" alt="">
            </div>
            
        </div>
        <div class="nav">
            <div class="circle-carrossel active"></div>
            <div class="circle-carrossel"></div>
            <div class="circle-carrossel"></div>
        </div>
    </div>
    
    <div class="textoUm">
        <h1 class="titulos">Nossa <span class="barraLaranja">História</span></h1>
        <p id="descricaoUm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            incididunt ut labore et
            dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
    </div>
</div>

<div class="containerDois">
    <div class="textoDois">
        <h1 class="titulos">Nossos <span class="barraLaranja">Valores</span></h1>
        <p id="descricaoDois">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
            incididunt ut labore et
            dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
    </div>

    <div class="container">
        <div class="carrossel carrossel-tam1">
            <div class="img-carrossel1 img4">
                <img src="../../static/img/sobre/PH VAL 001.jpg" alt="">
            </div>
            <div class="img-carrossel1 img5">
                <img src="../../static/img/sobre/PH VAL 002.jpg" alt="">
            </div>
            <div class="img-carrossel1 img6">
                <img src="../../static/img/sobre/PH VAL 003.jpg" alt="">
            </div>
            
        </div>
        <div class="nav">
            <div class="circle-carrossel1 active1"></div>
            <div class="circle-carrossel1"></div>
            <div class="circle-carrossel1"></div>
        </div>
    </div>

</div>
<div class="containerTres">
    <div id="background">
        <h1 id="titulo3"><span class="barraLaranja">Os melhores</span> professores do mercado</h1>
        <p id="texto3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien, est felis, sagittis viverra
            nulla mattis scelerisque. Eget cras integer.</p>
    </div>
</div>
<div class="containerQuatro">
    <h1 id="titulo4">Nossa Equipe</h1>
    <p id="texto4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed scelerisque elit. Sed
        eget tincidunt augue, nec tempus tellus. Quisque quis felis in felis posuere interdum.</p>
    <div class="containerImagens">
        {% for professor in professores %}
            <div class="conjunto">
                <img src="{{professor.imagem.url}}">
                <h2 class="nomes">{{professor.nome}}</h2>
                <h3 class="formacoes">{{professor.get_titulacao_display}} EM {{professor.curso.nome}}</h3>
                <h4 class="legenda">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </h4>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

{% block script %}
    <script src="{% static 'js/carrossel.js' %}"></script>
    <script src="{% static 'js/carrossel1.js' %}"></script>
{% endblock %}